/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './page2';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '@angular/http/src/http';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import18 from '@angular/core/src/linker/query_list';
import * as import19 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import25 from 'ionic-angular/config/config';
import * as import26 from '@angular/core/src/linker/element_ref';
import * as import27 from 'ionic-angular/navigation/view-controller';
import * as import28 from 'ionic-angular/components/app/app';
import * as import29 from 'ionic-angular/components/menu/menu-controller';
import * as import30 from 'ionic-angular/components/toolbar/toolbar';
import * as import31 from 'ionic-angular/util/keyboard';
import * as import32 from '@angular/core/src/zone/ng_zone';
import * as import33 from 'ionic-angular/components/tabs/tabs';
import * as import34 from 'ionic-angular/gestures/gesture-controller';
import * as import35 from 'ionic-angular/util/form';
import * as import36 from 'ionic-angular/components/item/item-reorder';
import * as import37 from 'ionic-angular/components/icon/icon';
import * as import38 from 'ionic-angular/components/button/button';
import * as import39 from 'ionic-angular/components/menu/menu-toggle';
import * as import40 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import41 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import42 from 'ionic-angular/components/navbar/navbar';
import * as import43 from 'ionic-angular/components/label/label';
import * as import44 from 'ionic-angular/components/item/item';
import * as import45 from 'ionic-angular/components/list/list';
import * as import46 from 'ionic-angular/components/content/content';
export class Wrapper_Page2 {
  context:import0.Page2;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.Page2(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_Page2_Host:import2.RenderComponentType = (null as any);
class _View_Page2_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Page2_0_4:Wrapper_Page2;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Page2_Host0,renderType_Page2_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-page2',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Page20(this.viewUtils,this.injector(0),this._appEl_0);
    this._Page2_0_4 = new Wrapper_Page2(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.Http));
    this._appEl_0.initComponent(this._Page2_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._Page2_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Page2) && (0 === requestNodeIndex))) { return this._Page2_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Page2_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Page2_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_Page2_Host === (null as any))) { (renderType_Page2_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_Page2_Host0(viewUtils,parentInjector,declarationEl);
}
export const Page2NgFactory:import12.ComponentFactory<import0.Page2> = new import12.ComponentFactory<import0.Page2>('page-page2',viewFactory_Page2_Host0,import0.Page2);
const styles_Page2:any[] = ([] as any[]);
var renderType_Page2:import2.RenderComponentType = (null as any);
class _View_Page20 extends import1.AppView<import0.Page2> {
  _el_0:any;
  _Header_0_3:import13.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import14.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import15.Wrapper_Button;
  _MenuToggle_4_5:import16.Wrapper_MenuToggle;
  _ToolbarItem_4_6:import17.Wrapper_ToolbarItem;
  _query_Button_4_0:import18.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import19.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _ToolbarTitle_9_4:import20.Wrapper_ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Content_14_4:import21.Wrapper_Content;
  _text_15:any;
  _el_16:any;
  _List_16_3:import22.Wrapper_List;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import3.AppElement;
  _Item_18_4:import23.Wrapper_Item;
  _ItemContent_18_5:import23.Wrapper_ItemContent;
  _query_Label_18_0:import18.QueryList<any>;
  _query_Button_18_1:import18.QueryList<any>;
  _query_Icon_18_2:import18.QueryList<any>;
  _text_19:any;
  _el_20:any;
  _Label_20_3:import24.Wrapper_Label;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import3.AppElement;
  _Item_24_4:import23.Wrapper_Item;
  _ItemContent_24_5:import23.Wrapper_ItemContent;
  _query_Label_24_0:import18.QueryList<any>;
  _query_Button_24_1:import18.QueryList<any>;
  _query_Icon_24_2:import18.QueryList<any>;
  _text_25:any;
  _el_26:any;
  _Label_26_3:import24.Wrapper_Label;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _Item_30_4:import23.Wrapper_Item;
  _ItemContent_30_5:import23.Wrapper_ItemContent;
  _query_Label_30_0:import18.QueryList<any>;
  _query_Button_30_1:import18.QueryList<any>;
  _query_Icon_30_2:import18.QueryList<any>;
  _text_31:any;
  _el_32:any;
  _Label_32_3:import24.Wrapper_Label;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  /*private*/ _appEl_36:import3.AppElement;
  _Item_36_4:import23.Wrapper_Item;
  _ItemContent_36_5:import23.Wrapper_ItemContent;
  _query_Label_36_0:import18.QueryList<any>;
  _query_Button_36_1:import18.QueryList<any>;
  _query_Icon_36_2:import18.QueryList<any>;
  _text_37:any;
  _el_38:any;
  _Label_38_3:import24.Wrapper_Label;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  /*private*/ _appEl_42:import3.AppElement;
  _Item_42_4:import23.Wrapper_Item;
  _ItemContent_42_5:import23.Wrapper_ItemContent;
  _query_Label_42_0:import18.QueryList<any>;
  _query_Button_42_1:import18.QueryList<any>;
  _query_Icon_42_2:import18.QueryList<any>;
  _text_43:any;
  _el_44:any;
  _Label_44_3:import24.Wrapper_Label;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_18:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Page20,renderType_Page2,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import13.Wrapper_Header(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import27.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','corejob');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import14.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import14.Wrapper_Navbar(this.parentInjector.get(import28.App),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import15.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import15.Wrapper_Button('','',this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import16.Wrapper_MenuToggle(this.parentInjector.get(import29.MenuController),new import26.ElementRef(this._el_4),this.parentInjector.get(import27.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_4_6 = new import17.Wrapper_ToolbarItem(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import30.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import18.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import19.Wrapper_Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import3.AppElement(9,2,this,this._el_9);
    var compView_9:any = import20.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import20.Wrapper_ToolbarTitle(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import30.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'Perfil',(null as any));
    compView_9.create(this._ToolbarTitle_9_4.context,[([] as any[]).concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_14 = new import3.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import21.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import21.Wrapper_Content(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import28.App),this.parentInjector.get(import31.Keyboard),this.parentInjector.get(import32.NgZone),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import33.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_16_3 = new import22.Wrapper_List(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_16),this.renderer,this.parentInjector.get(import34.GestureController));
    this._text_17 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','item item-block');
    this._appEl_18 = new import3.AppElement(18,16,this,this._el_18);
    var compView_18:any = import23.viewFactory_Item0(this.viewUtils,this.injector(18),this._appEl_18);
    this._Item_18_4 = new import23.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_18),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_18_5 = new import23.Wrapper_ItemContent();
    this._query_Label_18_0 = new import18.QueryList<any>();
    this._query_Button_18_1 = new import18.QueryList<any>();
    this._query_Icon_18_2 = new import18.QueryList<any>();
    this._appEl_18.initComponent(this._Item_18_4.context,([] as any[]),compView_18);
    this._text_19 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_20,'color','primary');
    this.renderer.setElementAttribute(this._el_20,'stacked','');
    this._Label_20_3 = new import24.Wrapper_Label(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_20),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'',(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_18_0.reset([this._Label_20_3.context]);
    this._Item_18_4.context.contentLabel = this._query_Label_18_0.first;
    compView_18.create(this._Item_18_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_20]),
      ([] as any[]).concat([
        this._text_19,
        this._text_22
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_23 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_16,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','item item-block');
    this._appEl_24 = new import3.AppElement(24,16,this,this._el_24);
    var compView_24:any = import23.viewFactory_Item0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Item_24_4 = new import23.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_24),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_24_5 = new import23.Wrapper_ItemContent();
    this._query_Label_24_0 = new import18.QueryList<any>();
    this._query_Button_24_1 = new import18.QueryList<any>();
    this._query_Icon_24_2 = new import18.QueryList<any>();
    this._appEl_24.initComponent(this._Item_24_4.context,([] as any[]),compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_26,'color','primary');
    this.renderer.setElementAttribute(this._el_26,'stacked','');
    this._Label_26_3 = new import24.Wrapper_Label(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_26),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_24_0.reset([this._Label_26_3.context]);
    this._Item_24_4.context.contentLabel = this._query_Label_24_0.first;
    compView_24.create(this._Item_24_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_26]),
      ([] as any[]).concat([
        this._text_25,
        this._text_28
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_29 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_16,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','item item-block');
    this._appEl_30 = new import3.AppElement(30,16,this,this._el_30);
    var compView_30:any = import23.viewFactory_Item0(this.viewUtils,this.injector(30),this._appEl_30);
    this._Item_30_4 = new import23.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_30),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_30_5 = new import23.Wrapper_ItemContent();
    this._query_Label_30_0 = new import18.QueryList<any>();
    this._query_Button_30_1 = new import18.QueryList<any>();
    this._query_Icon_30_2 = new import18.QueryList<any>();
    this._appEl_30.initComponent(this._Item_30_4.context,([] as any[]),compView_30);
    this._text_31 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_32,'color','primary');
    this.renderer.setElementAttribute(this._el_32,'stacked','');
    this._Label_32_3 = new import24.Wrapper_Label(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_32),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_30_0.reset([this._Label_32_3.context]);
    this._Item_30_4.context.contentLabel = this._query_Label_30_0.first;
    compView_30.create(this._Item_30_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_32]),
      ([] as any[]).concat([
        this._text_31,
        this._text_34
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_35 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_16,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','item item-block');
    this._appEl_36 = new import3.AppElement(36,16,this,this._el_36);
    var compView_36:any = import23.viewFactory_Item0(this.viewUtils,this.injector(36),this._appEl_36);
    this._Item_36_4 = new import23.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_36),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_36_5 = new import23.Wrapper_ItemContent();
    this._query_Label_36_0 = new import18.QueryList<any>();
    this._query_Button_36_1 = new import18.QueryList<any>();
    this._query_Icon_36_2 = new import18.QueryList<any>();
    this._appEl_36.initComponent(this._Item_36_4.context,([] as any[]),compView_36);
    this._text_37 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_38,'color','primary');
    this.renderer.setElementAttribute(this._el_38,'stacked','');
    this._Label_38_3 = new import24.Wrapper_Label(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_38),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'',(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_36_0.reset([this._Label_38_3.context]);
    this._Item_36_4.context.contentLabel = this._query_Label_36_0.first;
    compView_36.create(this._Item_36_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_38]),
      ([] as any[]).concat([
        this._text_37,
        this._text_40
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_41 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_16,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','item item-block');
    this._appEl_42 = new import3.AppElement(42,16,this,this._el_42);
    var compView_42:any = import23.viewFactory_Item0(this.viewUtils,this.injector(42),this._appEl_42);
    this._Item_42_4 = new import23.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_42),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_42_5 = new import23.Wrapper_ItemContent();
    this._query_Label_42_0 = new import18.QueryList<any>();
    this._query_Button_42_1 = new import18.QueryList<any>();
    this._query_Icon_42_2 = new import18.QueryList<any>();
    this._appEl_42.initComponent(this._Item_42_4.context,([] as any[]),compView_42);
    this._text_43 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_44,'color','primary');
    this.renderer.setElementAttribute(this._el_44,'stacked','');
    this._Label_44_3 = new import24.Wrapper_Label(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_44),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'',(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_42_0.reset([this._Label_44_3.context]);
    this._Item_42_4.context.contentLabel = this._query_Label_42_0.first;
    compView_42.create(this._Item_42_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_44]),
      ([] as any[]).concat([
        this._text_43,
        this._text_46
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_47 = this.renderer.createText(this._el_16,'\n  ',(null as any));
    this._text_48 = this.renderer.createText((null as any),'\n',(null as any));
    compView_14.create(this._Content_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_15,
        this._el_16,
        this._text_48
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_49 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import38.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import39.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5.context; }
    if (((token === import40.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6.context; }
    if (((token === import41.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4.context; }
    if (((token === import42.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4.context; }
    if (((token === import30.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3.context; }
    if (((token === import43.Label) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Label_20_3.context; }
    if (((token === import44.Item) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Item_18_4.context; }
    if (((token === import44.ItemContent) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._ItemContent_18_5.context; }
    if (((token === import43.Label) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Label_26_3.context; }
    if (((token === import44.Item) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Item_24_4.context; }
    if (((token === import44.ItemContent) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._ItemContent_24_5.context; }
    if (((token === import43.Label) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Label_32_3.context; }
    if (((token === import44.Item) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Item_30_4.context; }
    if (((token === import44.ItemContent) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ItemContent_30_5.context; }
    if (((token === import43.Label) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Label_38_3.context; }
    if (((token === import44.Item) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Item_36_4.context; }
    if (((token === import44.ItemContent) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._ItemContent_36_5.context; }
    if (((token === import43.Label) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Label_44_3.context; }
    if (((token === import44.Item) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._Item_42_4.context; }
    if (((token === import44.ItemContent) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._ItemContent_42_5.context; }
    if (((token === import45.List) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._List_16_3.context; }
    if (((token === import46.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Content_14_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_0:any = 'corejob';
    this._Navbar_2_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_4:any = '';
    this._MenuToggle_4_5.check_menuToggle(currVal_4,throwOnChange,false);
    this._MenuToggle_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_6.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_6:any = 'menu';
    this._Icon_6_3.check_name(currVal_6,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    if (this._Content_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    this._List_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    if (this._Item_18_4.detectChangesInternal(this,this._el_18,throwOnChange)) { this._appEl_18.componentView.markAsCheckOnce(); }
    this._ItemContent_18_5.detectChangesInternal(this,this._el_18,throwOnChange);
    const currVal_9:any = 'primary';
    this._Label_20_3.check_color(currVal_9,throwOnChange,false);
    this._Label_20_3.detectChangesInternal(this,this._el_20,throwOnChange);
    if (this._Item_24_4.detectChangesInternal(this,this._el_24,throwOnChange)) { this._appEl_24.componentView.markAsCheckOnce(); }
    this._ItemContent_24_5.detectChangesInternal(this,this._el_24,throwOnChange);
    const currVal_11:any = 'primary';
    this._Label_26_3.check_color(currVal_11,throwOnChange,false);
    this._Label_26_3.detectChangesInternal(this,this._el_26,throwOnChange);
    if (this._Item_30_4.detectChangesInternal(this,this._el_30,throwOnChange)) { this._appEl_30.componentView.markAsCheckOnce(); }
    this._ItemContent_30_5.detectChangesInternal(this,this._el_30,throwOnChange);
    const currVal_13:any = 'primary';
    this._Label_32_3.check_color(currVal_13,throwOnChange,false);
    this._Label_32_3.detectChangesInternal(this,this._el_32,throwOnChange);
    if (this._Item_36_4.detectChangesInternal(this,this._el_36,throwOnChange)) { this._appEl_36.componentView.markAsCheckOnce(); }
    this._ItemContent_36_5.detectChangesInternal(this,this._el_36,throwOnChange);
    const currVal_15:any = 'primary';
    this._Label_38_3.check_color(currVal_15,throwOnChange,false);
    this._Label_38_3.detectChangesInternal(this,this._el_38,throwOnChange);
    if (this._Item_42_4.detectChangesInternal(this,this._el_42,throwOnChange)) { this._appEl_42.componentView.markAsCheckOnce(); }
    this._ItemContent_42_5.detectChangesInternal(this,this._el_42,throwOnChange);
    const currVal_17:any = 'primary';
    this._Label_44_3.check_color(currVal_17,throwOnChange,false);
    this._Label_44_3.detectChangesInternal(this,this._el_44,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4.context]);
        this._ToolbarItem_4_6.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Button_18_1.dirty) {
        this._query_Button_18_1.reset(([] as any[]));
        this._Item_18_4.context._buttons = this._query_Button_18_1;
        this._query_Button_18_1.notifyOnChanges();
      }
      if (this._query_Icon_18_2.dirty) {
        this._query_Icon_18_2.reset(([] as any[]));
        this._Item_18_4.context._icons = this._query_Icon_18_2;
        this._query_Icon_18_2.notifyOnChanges();
      }
      if (this._query_Button_24_1.dirty) {
        this._query_Button_24_1.reset(([] as any[]));
        this._Item_24_4.context._buttons = this._query_Button_24_1;
        this._query_Button_24_1.notifyOnChanges();
      }
      if (this._query_Icon_24_2.dirty) {
        this._query_Icon_24_2.reset(([] as any[]));
        this._Item_24_4.context._icons = this._query_Icon_24_2;
        this._query_Icon_24_2.notifyOnChanges();
      }
      if (this._query_Button_30_1.dirty) {
        this._query_Button_30_1.reset(([] as any[]));
        this._Item_30_4.context._buttons = this._query_Button_30_1;
        this._query_Button_30_1.notifyOnChanges();
      }
      if (this._query_Icon_30_2.dirty) {
        this._query_Icon_30_2.reset(([] as any[]));
        this._Item_30_4.context._icons = this._query_Icon_30_2;
        this._query_Icon_30_2.notifyOnChanges();
      }
      if (this._query_Button_36_1.dirty) {
        this._query_Button_36_1.reset(([] as any[]));
        this._Item_36_4.context._buttons = this._query_Button_36_1;
        this._query_Button_36_1.notifyOnChanges();
      }
      if (this._query_Icon_36_2.dirty) {
        this._query_Icon_36_2.reset(([] as any[]));
        this._Item_36_4.context._icons = this._query_Icon_36_2;
        this._query_Icon_36_2.notifyOnChanges();
      }
      if (this._query_Button_42_1.dirty) {
        this._query_Button_42_1.reset(([] as any[]));
        this._Item_42_4.context._buttons = this._query_Button_42_1;
        this._query_Button_42_1.notifyOnChanges();
      }
      if (this._query_Icon_42_2.dirty) {
        this._query_Icon_42_2.reset(([] as any[]));
        this._Item_42_4.context._icons = this._query_Icon_42_2;
        this._query_Icon_42_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_18_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_24_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_30_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_36_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_42_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._MenuToggle_4_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._Content_14_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_10:any = import4.interpolate(1,'Id: ',this.context.userid,' ');
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setText(this._text_21,currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_12:any = import4.interpolate(1,'Rut: ',this.context.rut,' ');
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setText(this._text_27,currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_14:any = import4.interpolate(1,'Nombre: ',this.context.nombre,' ');
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setText(this._text_33,currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_16:any = import4.interpolate(2,'Apellidos: ',this.context.apaterno,' ',this.context.amaterno,' ');
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setText(this._text_39,currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_18:any = import4.interpolate(1,'Email: ',this.context.email,' ');
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setText(this._text_45,currVal_18);
      this._expr_18 = currVal_18;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._Content_14_4.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.context.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Page20(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.Page2> {
  if ((renderType_Page2 === (null as any))) { (renderType_Page2 = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_Page2,{})); }
  return new _View_Page20(viewUtils,parentInjector,declarationEl);
}